### ISSUE TITLE
AreaOfUse bounding coordinates are null after registry.init()

### ISSUE THREAD

**Issue by perrygeo** [geo-data/python-epsg#1]
I created a registry according to [these instructions](https://github.com/geo-data/python-epsg#persisting-registries), saving the result to a sqlite db. The AreaOfUse table shows all nulls for the east, west, north and south Bounding coordinates. Any idea why these values were not fetched from the epsg database?

**Comment by homme** [comment]
@perrygeo thanks for reporting this.  The problem was that the bounds weren't being loaded from the XML returned by the registry (namespace issue).  The above commit fixes the problem.

**Comment by perrygeo** [comment]
@homme Thanks, that works, the data is now in the `AreaOfUse` table. 

However, I'm not able to query it through the ORM though.

```
registry.session.query(schema.ProjectedCRS).filter(schema.ProjectedCRS.domainOfValidity.eastBoundLongitude.between(-76,-75)).all()
*** AttributeError: Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with ProjectedCRS.domainOfValidity has an attribute 'eastBoundLongitude'
```

If I grab the ProjectedCRS directly, it has a `domainOfValidity.eastBoundLogitude`... can you advise me on how to query for it? 

```
>>> test = registry.session.query(schema.ProjectedCRS).filter(schema.ProjectedCRS.identifier.ilike('%EPSG::6594')).all()[0]
>>> test.domainOfValidity.eastBoundLongitude
-75.31
```

**Comment by homme** [comment]
@perrygeo The root of the problem is that the `eastBoundLongitude` attribute is not present in the `schema.ProjectedCRS.domainOfValidity` object: you can only filter by attributes that explictly exist in the schema.  `schema.ProjectedCRS.domainOfValidity` is itself an attribute of `schema.ProjectedCRS` defining the relationship with `schema.AreaOfUse`.  The solution is to represent this relationship in the query using a join:

```
registry.session.query(schema.ProjectedCRS).join(schema.ProjectedCRS.domainOfValidity).filter(schema.AreaOfUse.eastBoundLongitude.between(-76,-75)).all()
```

Incidentally, you can use `filter_by()` to get specific matches as in your second example:

```
registry.session.query(schema.ProjectedCRS).filter_by(identifier = 'urn:ogc:def:crs:EPSG::6594').first()
```

I'll add these examples to the README.
